spring:
  application:
    name: StudyConnect
  datasource:
    url: jdbc:postgresql://localhost:5432/studyconnectdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${JWT_SECRET:bXlTdXBlclNlY3JldEtleUZvckp3dFRva2VuMTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaYWJjZGVmZ2hpams=}
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

logging:
  level:
    org.springframework.security: DEBUG
    com.StudyConnect.security: DEBUG
